### ISSUE TITLE
Meson build/config issue??

### ISSUE THREAD

**Issue by salamanderrake** [her001/Asma#13]
I am getting this message with the line
meson builddir

Meson encountered an error in file meson.build, line 3, column 0:
Unknown function "add_project_link_arguments".

Side Note:
What was wrong with cmake?

**Comment by her001** [comment]
Thanks for the report!

Could you try replacing line 3 in `meson.build` with:

```meson
add_global_link_arguments('-export-dynamic', language: 'c')
``` 

I am certain that the error is caused by your Meson version being too old. I do not intend on changing this, because there are good reasons to use the project function instead of the global one. I did find the version of Meson that this command was added though, and will list that as a minimum requirement.

Regarding CMake, nothing was wrong with it. For Asma, using one or the other shouldn't have much of an impact overall, but I didn't want to continue maintaining two build systems. I chose to drop CMake to force myself to learn Meson a little better.

**Comment by salamanderrake** [comment]
I got it, pretty simple, the version from apt was too old, had to install using pip3.

**Comment by salamanderrake** [comment]
And yes, its 16.04

**Comment by her001** [comment]
Cool, I'm glad it is working.
